
Config:
  SilentServer: false
  Nickprefix: '&a'
  Nicknames:
  - 'xZaboR'
  - 'MksQed'
  - 'Dempi'
  - 'ChocohGirl_0w0'
  - 'JJegan'
  - 'Cuzim_Passwort13'
  - 'Rosamie'
  - '7xR'
  - 'Veylh'
  - 'theSolus'
  - 'analpirat24'
  - 'Cuzim_Passswort13'
  - 'XXXTINGUISHED'
  - 'Minwoo_Park'
  - 'GatinhoMal1239'
  - 'Sooft'
  - 'FeroYT'
  - 'ItsM1_'
  - '_ectoBiologist__'
  - 'GeoXD'
  - 'MrChichh'
  - 'YOSjuIcE'
  - '_Typical'
  - 'MrLlamaCorn'
  - 'haxshwk'
  - 'xXRavennaXX'
  - 'xIkarioss'
  - 'StarrIsAnOtaku'
  - 'TWC_MartinPro'
  - 'RosesAreR3d'
  - 'Pingg_VN'
  - 'jobumjun1'
  - 'Shugart67'
  - 'stupidlycute_'
  - 'Gamer_2004_mo'
  - 'Lohan_'
  - 'mxCRAZY'
  - 'Galaxyy2K'
  - 'DontTalkToMe__'
  - 'BoogieMonsta'
  - 'Mioju_'
  - 'Pyro_Wrecks'
  - 'RootPlayz'
  - 'iTzJose_7w7'
  - 'Nintenny'
  - 'BardHCF'
  - 'KpopPandaz'
  - 'Toy_BonnieBlue'
  - 'xEthanz'
  - 'Rachael_Graine'
  - 'limeyhugs'
  - 'SiropXD'
  - 'IKORIIZ'
  - 'Seth_Ambrose'
  - 'arthurgamer14'
  - 'AForgottenUser'
  - 'ToxicNekoWolf_YT'
  - 'abxndoned'
  - 'lunatic555'
  - 'angus8888'
  - '_Uruloki_'
  - 'Isabell_Potato'
  - 'Michael_Pratt'
  - '1st_Mate_Mangle'


  #Namen alle existend stundenlang gesucht von mir dem fähigen Julian199
